// priority: 0

console.info('Hello, World! (You will only see this line once in console, during startup)')


  StartupEvents.registry('armor_tiers', event => {
    let armorTiers = [
        //[name, durability, [slotProtections], enchantmentValue, equipsound, repairIngredient, toughness, knockbackResistance
        ["gullhorn", 40, [1, 3, 2, 1], 15, "leather", "kubejs:gullhorn_hide", 2.0, 0.0],
        ["steel", 55, [2, 7, 6, 4], 22, "iron", "kubejs:steel_ingot", 1.0, 0.05],
        ["typhonite", 40, [5, 10, 8, 5], 25, "diamond", "kubejs:typhonite_ingot", 5.5, .25],
        ["carbide", 40, [3.5, 9, 6.5, 4], 15, "diamond", "kubejs:carbide_ingot", 3.0, .1]
    ]

//    armorTiers.forEach(type => {
//        event.add(type[0], tier => {
 //           tier.durabilityMultiplier = type[1]
//            tier.slotProtections = type[2] 
//            tier.enchantmentValue = type[3]
//            tier.equipSound = 'minecraft:item.armor.equip_'+type[4]
//            tier.repairIngredient = type[5]
//            tier.toughness = type[6]
//            tier.knockbackResistance = type[7]
        })
//	})});


  StartupEvents.registry('item', event => {
	// Register new items here
	// event.create('example_item').displayName('Example Item')

	//General Items
	event.create('fraktan_war_club', 'sword').tier('netherite').attackDamageBaseline(10.0).displayName('Fraktan War Club')

	event.create('sentry_sword', 'sword').tier('iron').attackDamageBaseline(6.0).displayName('Sentry Sword')

	event.create('carbide_ingot', 'basic')
		.displayName('Carbide Ingot')
		.fireResistant(true)

	event.create('carbide_sheet', 'basic')
		.displayName('Carbide Sheet')
		.fireResistant(true)

	event.create('steel_ingot', 'basic')
		.displayName('Steel Ingot')
		.fireResistant(true)

	event.create('steel_sheet', 'basic')
		.displayName('Steel Sheet')
		.fireResistant(true)

	event.create('steel_nugget', 'basic')
		.displayName('Steel Nugget')
		.fireResistant(true)

	
	event.create('tin_ingot', 'basic')
		.displayName('Tin Ingot')
		.fireResistant(true)

	event.create('tin_sheet', 'basic')
		.displayName('Tin Sheet')
		.fireResistant(true)

	event.create('tin_nugget', 'basic')
		.displayName('Tin Nugget')
		.fireResistant(true)

	event.create('crushed_cassiterite_ore', 'basic')
		.displayName('Crushed Cassiterite Ore')
		.fireResistant(true)

		event.create('raw_cassiterite', 'basic')
		.displayName('Raw Cassiterite')
		.fireResistant(true)

	event.create('bronze_ingot', 'basic')
		.displayName('Bronze Ingot')
		.fireResistant(true)

	event.create('bronze_sheet', 'basic')
		.displayName('Bronze Sheet')
		.fireResistant(true)

	event.create('bronze_nugget', 'basic')
		.displayName('Bronze Nugget')
		.fireResistant(true)

	event.create('fluorite', 'basic')
		.displayName('Fluorite')
		.fireResistant(false)

	event.create('ruby', 'basic')
		.displayName('§eRuby')
		.fireResistant(false)

	event.create('jade', 'basic')
		.displayName('Jade')
		.fireResistant(false)

	event.create('jasper', 'basic')
		.displayName('Jasper')
		.fireResistant(false)

	event.create('ceramic_powder', 'basic')
		.displayName('Ceramic Powder')
		.fireResistant(false)

	event.create('purified_ceramic_powder', 'basic')
		.displayName('Purified Ceramic Powder')
		.fireResistant(false)

	event.create('hardened_ceramic', 'basic')
		.displayName('Hardened Ceramic')
		.fireResistant(true)

	event.create('advanced_battery', 'basic')
		.displayName('Advanced Battery')
		.fireResistant(false)

	event.create('vicious_fangs', 'basic')
		.displayName('Vicious Fangs')
		.fireResistant(false)

	event.create('niteya_hide', 'basic')
		.displayName('Niteya Hide')
		.fireResistant(false)

	event.create('gullhorn_hide', 'basic')
		.displayName('Gullhorn Hide')
		.fireResistant(false)

	event.create('packaged_mre', 'basic')
		.displayName('§ePackaged MRE')
		.tooltip('§7Shelf stable food for long distance travel. §3Meal must be prepared in the inventory')
		.fireResistant(false)

	event.create('deconstructor_part', 'basic')
		.displayName('§dDeconstructor Part')

	event.create('amalgamated_metal', 'basic')
		.displayName('§eAmalgamated Metal')
		.fireResistant(false)

	event.create('raw_uradyne_ore', 'basic')
		.displayName('§eRaw Uradyne Ore')
		.fireResistant(false)

	event.create('uradyne_ingot', 'basic')
		.displayName('§eUradyne Ingot')
		.fireResistant(false)

	event.create('uradyne_sheet', 'basic')
		.displayName('§eUradyne Sheet')
		.fireResistant(false)

	event.create('typhonite_ingot', 'basic')
		.displayName('§dTyphonite Ingot')
		.tooltip('§7An almost otherworldly superalloy. §3Can be used to make incredibly resilient equipment')
		.fireResistant(false)

	event.create('typhonite_sheet', 'basic')
		.displayName('§dTyphonite Sheet')
		.fireResistant(false)

	event.create('tempered_scales', 'basic')
		.displayName('§eTempered Scales')
		.fireResistant(false)

	event.create('severed_horn', 'basic')
		.displayName('§eSevered Horn')
		.fireResistant(false)

	event.create('unpowered_hellion_core', 'basic')
		.displayName('Unpowered Hellion Core')
		.fireResistant(true)

	event.create('minced_velocitrod_meat', 'basic')
		.displayName('Minced Velocitrod Meat')
		.fireResistant(false)

	event.create('speciality_gullhorn_cut', 'basic')
		.displayName('Speciality Gullhorn Cut')
		.fireResistant(false)


//Items for Ponder

	event.create('dummy_tetra_hammer', 'basic')
		.displayName('§eWooden Hammer Prop')

		event.create('dummy_tetra_holo', 'basic')
		.displayName('§eHolosphere Prop')

	event.create('robotic_types', 'basic')
		.displayName('§eRobotic Types')

	event.create('fraktan_types', 'basic')
		.displayName('§eFraktan Types')

	event.create('animal_types', 'basic')
		.displayName('§eAnimal Types')

	event.create('colonist_types', 'basic')
		.displayName('§eColonist Types')


// Armors


//Gullhorn
event.create('gullhorn_helmet', 'helmet')
.tier('gullhorn')
.displayName('Gullhorn Hat')

event.create('gullhorn_chestplate', 'chestplate')
.tier('gullhorn')
.displayName('Gullhorn Vest')

event.create('gullhorn_leggings', 'leggings')
.tier('gullhorn')
.displayName('Gullhorn Pants')

event.create('gullhorn_boots', 'boots')
.tier('gullhorn')
.displayName('Gullhorn Boots')

//Steel
event.create('steel_helmet', 'helmet')
.tier('steel')
.displayName('Steel Helmet')

event.create('steel_chestplate', 'chestplate')
.tier('steel')
.displayName('Steel Chestplate')

event.create('steel_leggings', 'leggings')
.tier('steel')
.displayName('Steel Leggings')

event.create('steel_boots', 'boots')
.tier('steel')
.displayName('Steel Boots')

//Carbide
event.create('carbide_helmet', 'helmet')
.tier('carbide')
.displayName('Carbide Helmet')

event.create('carbide_chestplate', 'chestplate')
.tier('carbide')
.displayName('Carbide Chestplate')

event.create('carbide_leggings', 'leggings')
.tier('carbide')
.displayName('Carbide Leggings')

event.create('carbide_boots', 'boots')
.tier('carbide')
.displayName('Carbide Boots')

//Typhonite
event.create('typhonite_helmet', 'helmet')
.tier('typhonite')
.displayName('Typhonite Helmet')

event.create('typhonite_chestplate', 'chestplate')
.tier('typhonite')
.displayName('Typhonite Chestplate')

event.create('typhonite_leggings', 'leggings')
.tier('typhonite')
.displayName('Typhonite Leggings')

event.create('typhonite_boots', 'boots')
.tier('typhonite')
.displayName('Typhonite Boots')




});



StartupEvents.registry('block', event => {
	// Register new blocks here
	// event.create('example_block').material('wood').hardness(1.0).displayName('Example Block')

	//General Blocks
	event.create('stained_wood')
		.material('wood')
  		.hardness(2.5)

	event.create('stained_wood_slab', 'slab')
		  .material('wood')
			.hardness(2.5)

	event.create('stained_wood_stairs', 'stairs')
			.material('wood')
			  .hardness(2.5)

	event.create('fabricator_casing')
		.material('metal')
		.textureSide(Direction.UP, 'kubejs:block/fabricator_casing_top')
		.textureSide(Direction.DOWN, 'kubejs:block/fabricator_casing_bottom')

	event.create('broken_fabricator')
		.material('metal')
		.textureSide(Direction.UP, 'kubejs:block/broken_fabricator_top')
		.textureSide(Direction.DOWN, 'kubejs:block/broken_fabricator_bottom')

	//Ores
	event.create('fluorite_ore')
		.material('stone')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_wood_tool')
		.requiresTool(true)
	
	event.create('ruby_ore')
		.material('stone')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

	event.create('jade_ore')
		.material('stone')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_stone_tool')
		.requiresTool(true)

	event.create('jasper_ore')
		.material('stone')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_stone_tool')
		.requiresTool(true)

	event.create('cassiterite_ore')
		.material('stone')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_stone_tool')
		.requiresTool(true)

	event.create('lower_abyss_portal_frame')
		.material('stone')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)
		.textureSide(Direction.UP, 'kubejs:block/lower_abyss_portal_frame_top')
		.textureSide(Direction.DOWN, 'kubejs:block/lower_abyss_portal_frame_bottom')

	event.create('scrap_metal_ore')
		.material('metal')
		.hardness(4.6)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_diamond_tool')
		.tagBlock('forge:needs_netherite_tool')
		.requiresTool(true)
		.textureSide(Direction.UP, 'kubejs:block/scrap_metal_ore_top')
		.textureSide(Direction.DOWN, 'kubejs:block/scrap_metal_ore_bottom')

	event.create('amalgam_ore')
		.material('stone')
		.hardness(4.3)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_diamond_tool')
		.tagBlock('forge:needs_netherite_tool')
		.requiresTool(true)

	event.create('uradyne_ore')
		.material('stone')
		.hardness(5)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_diamond_tool')
		.tagBlock('forge:needs_netherite_tool')
		.requiresTool(true)

		event.create('caution_stripes')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('caution_stripes_slab', 'slab')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('caution_stripes_stairs', 'stairs')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('caution_stripes_red')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('caution_stripes_red_slab', 'slab')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('caution_stripes_red_stairs', 'stairs')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('caution_stripes_white')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('caution_stripes_white_slab', 'slab')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('caution_stripes_white_stairs', 'stairs')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('caution_stripes_orange')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('caution_stripes_orange_slab', 'slab')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('caution_stripes_orange_stairs', 'stairs')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('blast_glass')
		.material('glass')
		.hardness(5)
		.resistance(1200)
		.defaultTranslucent()
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('blast_glass_slab', 'slab')
		.material('glass')
		.hardness(5)
		.resistance(1200)
		.defaultTranslucent()
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('blast_glass_stairs', 'stairs')
		.material('glass')
		.hardness(5)
		.resistance(1200)
		.defaultTranslucent()
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_light_block')
		.material('glass')
		.hardness(5)
		.resistance(1200)
		.lightLevel(1)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_light_block_slab', 'slab')
		.material('glass')
		.hardness(5)
		.resistance(1200)
		.lightLevel(1)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_light_block_stairs', 'stairs')
		.material('glass')
		.hardness(5)
		.resistance(1200)
		.lightLevel(1)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

//Metal Palettes

//Standard Dark Gray
		event.create('industrial_mesh')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_mesh_slab', 'slab')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_mesh_stairs', 'stairs')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_mesh_single_border')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_mesh_single_border_slab', 'slab')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_mesh_single_border_stairs', 'stairs')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_mesh_platform')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)
		.textureSide(Direction.UP, 'kubejs:block/industrial_mesh_platform_top')
		.textureSide(Direction.DOWN, 'kubejs:block/industrial_mesh')

		event.create('industrial_pillar')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)
		.textureSide(Direction.UP, 'kubejs:block/industrial_pillar_top')
		.textureSide(Direction.DOWN, 'kubejs:block/industrial_pillar_top')

		event.create('industrial_scaffold')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.defaultCutout()
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_wall_bolted')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_wall_bolted_slab', 'slab')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_wall_bolted_stairs', 'stairs')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_wall_bolted_hidden')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_wall_bolted_hidden_slab', 'slab')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_wall_bolted_hidden_stairs', 'stairs')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_wall_smooth')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_wall_smooth_slab', 'slab')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

		event.create('industrial_wall_smooth_stairs', 'stairs')
		.material('metal')
		.hardness(5)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

//Light Gray
event.create('light_gray_industrial_mesh')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_mesh_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_mesh_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_mesh_single_border')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_mesh_single_border_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_mesh_single_border_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_mesh_platform')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)
.textureSide(Direction.UP, 'kubejs:block/industrial_mesh_platform_top')
.textureSide(Direction.DOWN, 'kubejs:block/industrial_mesh')

event.create('light_gray_industrial_pillar')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)
.textureSide(Direction.UP, 'kubejs:block/light_gray_industrial_pillar_top')
.textureSide(Direction.DOWN, 'kubejs:block/light_gray_industrial_pillar_top')

event.create('light_gray_industrial_scaffold')
.material('metal')
.hardness(5)
.resistance(1200)
.defaultCutout()
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_wall_bolted')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_wall_bolted_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_wall_bolted_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_wall_bolted_hidden')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_wall_bolted_hidden_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_wall_bolted_hidden_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_wall_smooth')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_wall_smooth_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('light_gray_industrial_wall_smooth_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

//Colored Minipalette (Red)
event.create('red_industrial_wall_bolted')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('red_industrial_wall_bolted_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('red_industrial_wall_bolted_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('red_industrial_wall_bolted_hidden')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('red_industrial_wall_bolted_hidden_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('red_industrial_wall_bolted_hidden_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('red_industrial_wall_smooth')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('red_industrial_wall_smooth_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('red_industrial_wall_smooth_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

//Colored Minipalette (Blue)
event.create('blue_industrial_wall_bolted')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('blue_industrial_wall_bolted_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('blue_industrial_wall_bolted_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('blue_industrial_wall_bolted_hidden')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('blue_industrial_wall_bolted_hidden_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('blue_industrial_wall_bolted_hidden_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('blue_industrial_wall_smooth')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('blue_industrial_wall_smooth_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('blue_industrial_wall_smooth_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

//Colored Minipalette (Yellow)
event.create('yellow_industrial_wall_bolted')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('yellow_industrial_wall_bolted_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('yellow_industrial_wall_bolted_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('yellow_industrial_wall_bolted_hidden')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('yellow_industrial_wall_bolted_hidden_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('yellow_industrial_wall_bolted_hidden_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('yellow_industrial_wall_smooth')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('yellow_industrial_wall_smooth_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('yellow_industrial_wall_smooth_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

//Colored Minipalette (Green)
event.create('green_industrial_wall_bolted')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('green_industrial_wall_bolted_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('green_industrial_wall_bolted_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('green_industrial_wall_bolted_hidden')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('green_industrial_wall_bolted_hidden_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('green_industrial_wall_bolted_hidden_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('green_industrial_wall_smooth')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('green_industrial_wall_smooth_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('green_industrial_wall_smooth_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

//Colored Minipalette (Purple)
event.create('purple_industrial_wall_bolted')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('purple_industrial_wall_bolted_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('purple_industrial_wall_bolted_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('purple_industrial_wall_bolted_hidden')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('purple_industrial_wall_bolted_hidden_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('purple_industrial_wall_bolted_hidden_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('purple_industrial_wall_smooth')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('purple_industrial_wall_smooth_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('purple_industrial_wall_smooth_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

//Colored Minipalette (Magenta)
event.create('magenta_industrial_wall_bolted')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('magenta_industrial_wall_bolted_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('magenta_industrial_wall_bolted_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('magenta_industrial_wall_bolted_hidden')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('magenta_industrial_wall_bolted_hidden_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('magenta_industrial_wall_bolted_hidden_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('magenta_industrial_wall_smooth')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('magenta_industrial_wall_smooth_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('magenta_industrial_wall_smooth_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

//Colored Minipalette (Cyan)
event.create('cyan_industrial_wall_bolted')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('cyan_industrial_wall_bolted_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('cyan_industrial_wall_bolted_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('cyan_industrial_wall_bolted_hidden')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('cyan_industrial_wall_bolted_hidden_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('cyan_industrial_wall_bolted_hidden_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('cyan_industrial_wall_smooth')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('cyan_industrial_wall_smooth_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('cyan_industrial_wall_smooth_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

//Colored Minipalette (Lime)
event.create('lime_industrial_wall_bolted')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('lime_industrial_wall_bolted_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('lime_industrial_wall_bolted_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('lime_industrial_wall_bolted_hidden')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('lime_industrial_wall_bolted_hidden_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('lime_industrial_wall_bolted_hidden_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('lime_industrial_wall_smooth')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('lime_industrial_wall_smooth_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('lime_industrial_wall_smooth_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

//Colored Minipalette (Brown)
event.create('brown_industrial_wall_bolted')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('brown_industrial_wall_bolted_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('brown_industrial_wall_bolted_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('brown_industrial_wall_bolted_hidden')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('brown_industrial_wall_bolted_hidden_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('brown_industrial_wall_bolted_hidden_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('brown_industrial_wall_smooth')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('brown_industrial_wall_smooth_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('brown_industrial_wall_smooth_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

//Colored Minipalette (Black)
event.create('black_industrial_wall_bolted')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('black_industrial_wall_bolted_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('black_industrial_wall_bolted_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('black_industrial_wall_bolted_hidden')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('black_industrial_wall_bolted_hidden_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('black_industrial_wall_bolted_hidden_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('black_industrial_wall_smooth')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('black_industrial_wall_smooth_slab', 'slab')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)

event.create('black_industrial_wall_smooth_stairs', 'stairs')
.material('metal')
.hardness(5)
.resistance(1200)
.tagBlock('minecraft:mineable/pickaxe')
.tagBlock('minecraft:needs_iron_tool')
.requiresTool(true)


})

BlockEvents.modification(event => {
	event.modify('minecraft:crafting_table', block => {
	  block.soundType = 'metal'
	})
	//event.modify('minecraft:end_portal_frame', block => {
	//	block.destroySpeed = 3.1
	//	.tagBlock("mineable/pickaxe")
	//	.tagBlock("needs_diamond_tool")
	 // })
})
