
["Combustion Reactor"]
	#The time interval consumed each time: time>-11
	Time = 0.0
	#Show time left of reactor in inventury
	"Tip in inventury" = true

["Brass plates"]
	#change armor value
	Armor = 2.0
	#change toughness value
	Toughness = 4.0
	#change weight value
	Weight = 2.0

["Iron plates"]
	#change armor value
	Armor = 4.0
	#change toughness value
	Toughness = 6.0
	#change weight value
	Weight = 1.0

["Alloy plates"]
	#change armor value
	Armor = 6.0
	#change toughness value
	Toughness = 8.0
	#change weight value
	Weight = 1.5

